version: '3.8'

services:
  redis:
    image: redis/redis-stack:latest
    container_name: cyber-warrior-redis
    ports:
      - "6379:6379"    # Redis server
      - "8001:8001"    # Redis Insight web UI
    volumes:
      - ./.redisdata:/data
    restart: unless-stopped
    command: redis-server --save 60 1 --loglevel notice --requirepass ""
